package ar.edu.unju.fi.model;



import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable, Cloneable{

	
	private static final long serialVersionUID = -1203089025474765120L;
	private int pedidoId;
	private Date fechaPedido;
	private Double total;
	private String estado;
	private Integer usuarioCreacion;
	private Date fechaCreacion;
	private Integer usuarioModificacion;
	private Date fechaModificacion;
	private Set detallePedidos = new HashSet(0);

	public Pedido() {
	}

	public Pedido(int pedidoId) {
		this.pedidoId = pedidoId;
	}

	public Pedido(int pedidoId, Date fechaPedido, Double total,
			String estado, Integer usuarioCreacion, Date fechaCreacion,
			Integer usuarioModificacion, Date fechaModificacion,
			Set detallePedidos) {
		this.pedidoId = pedidoId;
		this.fechaPedido = fechaPedido;
		this.total = total;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.detallePedidos = detallePedidos;
	}

	public int getPedidoId() {
		return this.pedidoId;
	}

	public void setPedidoId(int pedidoId) {
		this.pedidoId = pedidoId;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public Double getTotal() {
		Double totalPedido=0d;
		Iterator<DetallePedido> it = detallePedidos.iterator();
        while(it.hasNext()) {
        	totalPedido+=((DetallePedido)it.next()).getPrecioUnitario();
        }
		
		return totalPedido;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Set getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set detallePedidos) {
		this.detallePedidos = detallePedidos;
	}
	
	public Pedido clone() throws CloneNotSupportedException{
		return (Pedido) super.clone();
	}
}
