package ar.edu.unju.fi.model;

// Generated 21-oct-2014 19:40:42 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String estado;
	private Date fechaVencimiento;
	private String descripcion;
	private BigDecimal precioFardo;
	private BigDecimal precioUnitario;
	private Integer stock;
	private String tamanio;
	private Set detallePedidos = new HashSet(0);

	public Producto() {
	}

	public Producto(int codigo) {
		this.codigo = codigo;
	}

	public Producto(int codigo, String nombre, String estado,
			Date fechaVencimiento, String descripcion, BigDecimal precioFardo,
			BigDecimal precioUnitario, Integer stock, String tamanio,
			Set detallePedidos) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.estado = estado;
		this.fechaVencimiento = fechaVencimiento;
		this.descripcion = descripcion;
		this.precioFardo = precioFardo;
		this.precioUnitario = precioUnitario;
		this.stock = stock;
		this.tamanio = tamanio;
		this.detallePedidos = detallePedidos;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getPrecioFardo() {
		return this.precioFardo;
	}

	public void setPrecioFardo(BigDecimal precioFardo) {
		this.precioFardo = precioFardo;
	}

	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public String getTamanio() {
		return this.tamanio;
	}

	public void setTamanio(String tamanio) {
		this.tamanio = tamanio;
	}

	public Set getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
