package ar.edu.unju.fi.model;



import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	
	private static final long serialVersionUID = 8900005601324290094L;
	private int codigo;
	private String nombre;
	private String estado;
	private Date fechaVencimiento;
	private String descripcion;
	private Double precioFardo;
	private Double precioUnitario;
	private Integer stock;
	private String tamanio;

	public Producto() {
	}

	public Producto(int codigo) {
		this.codigo = codigo;
	}

	public Producto(int codigo, String nombre, String estado,
			Date fechaVencimiento, String descripcion, Double precioFardo,
			Double precioUnitario, Integer stock, String tamanio) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.estado = estado;
		this.fechaVencimiento = fechaVencimiento;
		this.descripcion = descripcion;
		this.precioFardo = precioFardo;
		this.precioUnitario = precioUnitario;
		this.stock = stock;
		this.tamanio = tamanio;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getPrecioFardo() {
		return this.precioFardo;
	}

	public void setPrecioFardo(Double precioFardo) {
		this.precioFardo = precioFardo;
	}

	public Double getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(Double precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public String getTamanio() {
		return this.tamanio;
	}

	public void setTamanio(String tamanio) {
		this.tamanio = tamanio;
	}


}
