package ar.edu.unju.fi.model;

// Generated 21-oct-2014 19:40:42 by Hibernate Tools 3.4.0.CR1


/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {
	
	private static final long serialVersionUID = 2988694600020332108L;
	private int rolId;
	private String descripcion;
	
	public static String ADMINISTRADOR="ADMINISTRADOR";
	public static String VENDEDOR="VENDEDOR";
	
	
	public Rol() {
	}
	

	public Rol(int rolId) {
		this.rolId = rolId;
	}

	public Rol(int rolId, String descripcion) {
		this.rolId = rolId;
		this.descripcion = descripcion;
	}

	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	@Override
	public String toString() {
		return descripcion;
	}

}
